### ISSUE TITLE
ClassNotFoundException: javax.xml.bind.JAXBContext in java 9

### ISSUE THREAD

**Issue by YannickXiong** [wadle/MBT_GraphWalker_Python#1]
# Environment
- OS: mac 10.14.3 (18D109)
- java: java 9
Java(TM) SE Runtime Environment (build 9+181)

# Desc:
raise except `ClassNotFoundException: javax.xml.bind.JAXBContext` in java 9

# Logs
```
gw --debug all online --service RESTFUL -m ./model/test.graphml "random(edge_coverage(100))"
3月 13, 2019 3:20:23 下午 com.sun.jersey.server.impl.application.WebApplicationImpl _initiate
信息: Initiating Jersey application, version 'Jersey: 1.19.3 10/24/2016 03:43 PM'
An error occurred when running command: --debug all online --service RESTFUL -m ./model/test.graphml random(edge_coverage(100))
Type javax.xml.bind.JAXBContext not present

15:20:23.127 [main] ERROR org.graphwalker.cli.CLI - An error occurred when running command: --debug all online --service RESTFUL -m ./model/test.graphml random(edge_coverage(100))
java.lang.TypeNotPresentException: Type javax.xml.bind.JAXBContext not present
	at java.base/sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:117)
	at java.base/sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
	at java.base/sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at java.base/sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68)
	at java.base/sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138)
	at java.base/sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at java.base/sun.reflect.generics.repository.ClassRepository.computeSuperInterfaces(ClassRepository.java:117)
	at java.base/sun.reflect.generics.repository.ClassRepository.getSuperInterfaces(ClassRepository.java:95)
	at java.base/java.lang.Class.getGenericInterfaces(Class.java:1112)
	at com.sun.jersey.core.reflection.ReflectionHelper.getClass(ReflectionHelper.java:629)
	at com.sun.jersey.core.reflection.ReflectionHelper.getClass(ReflectionHelper.java:625)
	at com.sun.jersey.core.spi.factory.ContextResolverFactory.getParameterizedType(ContextResolverFactory.java:202)
	at com.sun.jersey.core.spi.factory.ContextResolverFactory.init(ContextResolverFactory.java:89)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._initiate(WebApplicationImpl.java:1332)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.access$700(WebApplicationImpl.java:180)
	at com.sun.jersey.server.impl.application.WebApplicationImpl$13.f(WebApplicationImpl.java:799)
	at com.sun.jersey.server.impl.application.WebApplicationImpl$13.f(WebApplicationImpl.java:795)
	at com.sun.jersey.spi.inject.Errors.processWithErrors(Errors.java:193)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:795)
	at com.sun.jersey.api.container.ContainerFactory.createContainer(ContainerFactory.java:172)
	at com.sun.jersey.api.container.ContainerFactory.createContainer(ContainerFactory.java:134)
	at com.sun.jersey.api.container.grizzly2.GrizzlyServerFactory.createHttpServer(GrizzlyServerFactory.java:243)
	at com.sun.jersey.api.container.grizzly2.GrizzlyServerFactory.createHttpServer(GrizzlyServerFactory.java:137)
	at org.graphwalker.cli.CLI.runCommandOnline(CLI.java:336)
	at org.graphwalker.cli.CLI.run(CLI.java:194)
	at org.graphwalker.cli.CLI.main(CLI.java:103)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBContext
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at java.base/sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114)
	... 25 common frames omitted
```

**Comment by wadle** [comment]
I am working on it.
Thank you.
